# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT

[files]
extend-exclude = [
    "src/test/resources/org/eolang/hone/rules/streams/lints/101-lints.phi",
    "src/test/resources/org/eolang/hone/rules/streams/lints/111-lints.phi"
]
