# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
architect:
  - yegor256
ec2:
  type: t2.2xlarge
docker:
  image: yegor256/java
assets:
  settings.xml: yegor256/objectionary-secrets#settings.xml
  pubring.gpg: yegor256/objectionary-secrets#pubring.gpg
  secring.gpg: yegor256/objectionary-secrets#secring.gpg
  docker-password: yegor256/objectionary-secrets#docker-password
merge:
  script: mvn clean install -DskipTests -Dinvoker.skip -Pqulice -e -B -Dstyle.color=never
release:
  pre: false
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    sed -i -e "s/0.0.0/${tag}/" src/site/apt/index.apt.vm
    git commit -am "${tag}"
    export MAVEN_OPTS="--add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED"
    mvn clean deploy -DskipTests -Dinvoker.skip -Pqulice,objectionary,sonatype -e -B -s ../settings.xml

    cat ../docker-password | sudo docker login --password-stdin -u yegor256
    cd src/main/resources/org/eolang/hone/scaffolding/
    cp ../rules/*.yml rules
    sed -i -e "s/\"0.0.0\"/\"${tag}\"/" Dockerfile
    sed -i -e "s/0.0.0/${tag}/" entry.sh
    git add Dockerfile
    git add entry.sh
    git commit -m "version set to ${tag}"
    repo=yegor256/hone
    sudo docker build "$(pwd)" --tag "${repo}:${tag}"
    sudo docker build "$(pwd)" --tag "${repo}:latest"
    sudo docker push "${repo}:${tag}"
    sudo docker push "${repo}:latest"
