# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: codecov
'on':
  push:
    branches:
      - master
    paths-ignore: [ 'README.md' ]
concurrency:
  group: codecov-${{ github.ref }}
  cancel-in-progress: true
jobs:
  codecov:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: docker --version
      - run: |
          sudo wget -q -O /usr/bin/phino http://phino.objectionary.com/releases/ubuntu-24.04/phino-latest
          sudo chmod a+x /usr/bin/phino
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - run: mvn clean install -ntp -Pjacoco -Pdeep -Dinvoker.skip --errors --batch-mode
      - uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
