# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: coverage
'on':
  push:
    branches:
      - master
    paths-ignore: [ 'README.md', '.github' ]
concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true
jobs:
  coverage:
    timeout-minutes: 90
    runs-on: ubuntu-24.04
    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 23
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ubuntu-jdk-23-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-jdk-23-maven-
      - run: |
          sudo wget -q -O /usr/bin/phino http://phino.objectionary.com/releases/ubuntu-24.04/phino-latest
          sudo chmod a+x /usr/bin/phino
      - run: |
          sudo apt-get update
          sudo apt-get install -y cloc
      - run: .github/coverage.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-pull-request@v8
        with:
          sign-commits: true
          branch: coverage
          commit-message: 'new coverage results'
          delete-branch: true
          title: 'New coverage results'
          assignees: yegor256
          base: master
