# The MIT License (MIT)
#
# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: shellcheck
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: shellcheck-${{ github.ref }}
  cancel-in-progress: true
jobs:
  shellcheck:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
